/**
 * MicroShop.IdentityAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RegisterDto { 
    fullName?: string | null;
    email?: string | null;
    role?: string | null;
    password?: string | null;
    userName?: string | null;
}

