/**
 * MicroShop.OrderAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OrderItemDto { 
    productId?: string;
    price?: number;
    quantity?: number;
    productName?: string | null;
}

