/**
 * MicroShop.StockAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Product } from './product';


export interface ProductPagedResponse { 
    data?: Array<Product> | null;
    pageNumber?: number;
    pageSize?: number;
    totalRecords?: number;
    totalPages?: number;
}

